config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :donations, only: [:create, :destroy]
    resources :reviews, only: [:create]
    resources :opinions, only: [:create, :update, :destroy]
  end
  devise_for :users
  root to: 'pages#home'
  resources :quizzes, only: [:new]
  resources :categories_prefs, only: [:create]
  resource :emotion_prefs, only: [:update]
  resource :temperature_prefs, only: [:update]
  resources :users, only: [:show]
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  def new
    @categories_pref = CategoriesPref.new
    authorize @categories_pref
  end

end

app/views/quizzes/new.html.erb
<div class="container-fluid side-margin">
  <div class="row margin-left">
    <div class="col-xs-12 col-sm-6 col-lg-8 col-sm-offset-3 col-lg-offset-2 align-h bottomize space-between margin-bottom">
      <!-- Article -->
      <div class="card-article">
        <!-- Articles informations -->
        <div class="article-text">
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-lg-8 col-sm-offset-3 col-lg-offset-2" id="quizz-title">
            <h3>Customize your feed</h3>
            <p>with your preferences</p>

            </div>
          </div>


   <!-- FORM FOR THE CATEGORIES-->
          <div id="new_categories_pref_wrapper">
            <hr>
            <h4>What subjects do you like to read about ?</h4>
            <%= simple_form_for @categories_pref, remote: true do |f| %>

              <div class="form-group margin-bottom">
                <div class="choices">

                  <div class="row">
                  <% Category.all.each do |category| %>
                    <div class="col-xs-12 col-sm-4">

                        <input type="checkbox" class="hidden" value="<%= category.id %>" name="categories_pref[category_id][]" id="categories_pref_category_id_<%= category.id %>">

                          <label for="categories_pref_category_id_<%= category.id %>" class="category-choice" style="background-image: url('<%= category.picture %>')" style="cursor: pointer;">
                            <%= category.name %>
                          </label>

                    </div>
                      <% end %>
                  </div>
                 </div>
              <div class="left-btn">
                <%= f.submit "Next", class: "btn-blue-border" %>
              </div>
              <% end %>
            </div>
          </div>

   <!-- FORM FOR THE EMOTION-PREF UPDATE OF USER-->
          <div id="edit_user_wrapper" class="hidden" data-user="<%= current_user.id %>">
            <hr>
            <h4>What kind of reading do you like ?</h4>

            <%= simple_form_for current_user, remote: true, url: emotion_prefs_path, method: :patch do |f| %>
            <div class="form-group margin-bottom">
              <div class="choices">
                <div class="row">

                  <div class="flex-container">
                    <div>
                      <div class="col-xs-12 col-sm-6 smiley">
                        <input type="radio" class="hidden" value="1" name="user[emotion_pref]" id="user_emotion_pref_1">
                          <label for="user_emotion_pref_1" class="smiley" style="background-image: url(<%= asset_path 'sad_smiley.png' %>); width:100px; height: 100px;" style="cursor: pointer;">
                          </label>
                      </div>

                      <div class="col-xs-12 col-sm-6 smiley">
                        <input type="radio" class="hidden" value="2" name="user[emotion_pref]" id="user_emotion_pref_2">
                          <label for="user_emotion_pref_2" class="smiley" style="background-image: url(<%= asset_path 'yay_smiley.png' %>); width:100px; height: 100px;" style="cursor: pointer;">
                          </label>
                      </div>
                    </div>

                    <div class="explanation">
                      <div id="emotion-min">
                        <p>Sad</p>
                      </div>
                      <div id="emotion-max">
                        <p>Happy</p>
                      </div>
                    </div>
                  </div>

                <!-- <div class="col-xs-6 col-sm-6">
                  <input type="radio" class="hidden" value="1" name="user[emotion_pref]" id="user_emotion_pref_1">
                    <label for="user_emotion_pref_1" class="emotion-choice" style="background-image: url('https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/3193bc935b5aefa5d9310cecc4a78554fe0a76b2_2880x1620.jpg?')" style="cursor: pointer;">Are China and the US doomed to conflict?
                    </label>
                    <p class="text-center">Are China and the US doomed to conflict?</p>
                  </div>-->

                <!--<div class="col-xs-6 col-sm-6">
                  <input type="radio" class="hidden" value="2" name="user[emotion_pref]" id="user_emotion_pref_2">
                    <label for="user_emotion_pref_2" class="emotion-choice" style="background-image: url('https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/016a827cc0757092a0439ab2a63feca8655b6c29_1600x1200.jpg?')" style="cursor: pointer;">The surprising science of happiness
                    </label>
                    <p class="text-center">The surprising science of happiness</p>
                  </div>-->
                </div>
              </div>
              <div class="left-btn">
                <%= f.submit "Next", class: "btn-blue-border" %>
              </div>

              <% end %>
            </div>
          </div>


   <!-- FORM FOR THE TEMPERATURE-PREF UPDATE OF USER-->
          <div id="temperature-form" class="hidden">
            <hr>
            <h4>What kind of debate do you prefer? </h4>
            <%= simple_form_for current_user, url: temperature_prefs_path, method: :patch do |f| %>
            <div class="form-group margin-bottom">
              <div class="choices">
                <div class="row">

                  <div class="col-xs-6 col-sm-3">
                    <input type="radio" class="hidden" value="1" name="user[temperature_pref]" id="user_temperature_pref_1">
                     <label for="user_temperature_pref_1" class="tempe-choice" style="background-image: url('https://media.giphy.com/media/AqniAO4dD28Sc/giphy.gif')" style="cursor: pointer;">Chill
                     </label>
                     <!--  <p class="text-center">Chill</p> -->
                  </div>

                  <div class="col-xs-6 col-sm-3">
                     <input type="radio" class="hidden" value="2" name="user[temperature_pref]" id="user_temperature_pref_2">
                       <label for="user_temperature_pref_2" class="tempe-choice" style="background-image: url('https://media.giphy.com/media/3ohhwrsMa5vLKra848/giphy.gif')" style="cursor: pointer;">Chill but doubful
                       </label>
                       <!--<p class="text-center">Chill but doubful</p>-->
                  </div>

                  <div class="col-xs-6 col-sm-3">
                    <input type="radio" class="hidden" value="3" name="user[temperature_pref]" id="user_temperature_pref_3">
                      <label for="user_temperature_pref_3" class="tempe-choice" style="background-image: url('https://media.giphy.com/media/htFDJG2MkJiqk/giphy.gif')" style="cursor: pointer;">Quite intense
                      </label>
                      <!--<p class="text-center">Ready to intervene</p>-->
                  </div>

                  <div class="col-xs-6 col-sm-3">
                    <input type="radio" class="hidden" value="4" name="user[temperature_pref]" id="user_temperature_pref_4">
                      <label for="user_temperature_pref_4" class="tempe-choice" style="background-image: url('https://media.giphy.com/media/7LgKUsZiSjcRO/giphy.gif')" style="cursor: pointer;">Pretty intense
                      </label>
                      <!--<p class="text-center">Pretty intense</p>-->
                  </div>

                </div>
              </div>
            </div>

            <div class="left-btn">
              <%= f.submit "Done", class: "btn-blue-border" %>
            </div>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>