config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :donations, only: [:create, :destroy]
    resources :reviews, only: [:create]
    resources :opinions, only: [:create, :update, :destroy]
  end
  devise_for :users
  root to: 'pages#home'
  resources :quizzes, only: [:new]
  resources :categories_prefs, only: [:create]
  resource :emotion_prefs, only: [:update]
  resource :temperature_prefs, only: [:update]
  resources :users, only: [:show]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :donations, dependent: :nullify
  has_many :users, through: :donations
  has_many :reviews, dependent: :destroy
  has_many :opinions, dependent: :destroy

  validates :title, :subtitle, :content, :picture, presence: true
  validates :summary, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }

  def self.this_categories_first(emotion, temperature, categories)
    # emotion statement
    specific_emotion = "CASE WHEN avg_emotion = #{emotion} THEN 0 ELSE 1 END"
    # temperature statement
    specific_temperature = "CASE WHEN avg_temperature = #{temperature} THEN 0 ELSE 1 END"
    # categories statement
    statement = ["CASE"]
    categories.each_with_index do |category, index|
      statement << "WHEN category_id = #{category.id} THEN #{index}"
    end
    statement << "ELSE #{categories.length} END"
    specific_order = statement.join(" ")
    whole_statement = [specific_emotion, specific_temperature, specific_order].join(", ")
    order(whole_statement)
  end

  include AlgoliaSearch

  algoliasearch do
    attribute :title, :subtitle, :content
    searchableAttributes ['title', 'subtitle', 'content']
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    filter_cat = params[:category]
    filter_temp = params[:avg_temperature]
    filter_emo = params[:avg_emotion]

      @category = Category.find_by_name(params[:category]) if filter_cat
      @articles = policy_scope(Article)
      @articles = @articles.where(category_id: @category.id) if @category
      @articles = @articles.where("avg_temperature > ? AND avg_temperature < ?", filter_temp.to_i - 0.5, filter_temp.to_i + 0.4 ) if filter_temp
      @articles = @articles.where("avg_emotion > ? AND avg_emotion < ?", filter_emo.to_i - 0.5, filter_emo.to_i + 0.4 ) if filter_emo
      @articles = @articles.where("title iLIKE ?", "%#{params[:query]}%") if params[:query].present?
    if current_user && current_user.answered
      @articles = @articles.this_categories_first(current_user.emotion_pref, current_user.temperature_pref, current_user.categories)
    else
      @articles = @articles.order(created_at: :desc)
    end
  end

  def show
    @avg_rating = @article.avg_rating
    @donation = Donation.new
    @opinion = Opinion.new
    @opinions = Opinion.where(article: @article)
    @review = Review.new
    @reviews = Review.where(article: @article)
    authorize @donation
  end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    authorize @article
    if @article.save
      redirect_to articles_path, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize @article
  end

  def update
    authorize @article
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @article
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :subtitle, :summary, :content, :picture, :category_id, :publishing_date)
  end
end

app/views/articles/_donation.html.erb
<h4> Thank you for your support <i class="fa fa-heart"></i></h4>
<div>
  <div class="confirmation-container" id="validation-anim">
    <svg id="Layer_2" class="on" viewBox="0 0 50 50"><defs><style>.cls-1{fill:none;stroke:#ddd;stroke-miterlimit:10;stroke-width:1px;}</style></defs><circle class="cls-1" cx="25" cy="25" r="19.27"/></svg>

    <svg id="Layer_1" class="on" viewBox="0 0 24 19"><defs><style>.cls-2{fill:none;stroke:lightgreen;stroke-miterlimit:10;stroke-width:3px;}</style></defs>
      <polyline class="cls-2" points="2.09 9.56 8.3 15.77 22.19 1.87"/>
    </svg>
  </div>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
<%= f.input :title, placeholder: "Title", label: false, input_html: { class: 'form_light no_border form_title' } %>
<%= f.input :subtitle, placeholder: "Subtitle", label: false, input_html: { class: 'form_light no_border form_subtitle margin-bottom' }%>
<div class='no_padding'>
  <%= f.input :content, placeholder: "What's your story?", label: false, input_html: { class: 'quill_container no_padding_left' }%>
</div>
<%= f.input :summary, placeholder: "Summary", label: false, input_html: { class: 'form_light no_border' } %>
<%= f.input :picture, placeholder: "Video/Picture URL", label: false, input_html: { class: 'form_light no_border' } %>
<div class="dropdown_wrapper">
  <%= f.association :category, prompt: "Choose a category", label: false, input_html: { class: 'form_light no_border no_padding margin-bottom' }%>
</div>
<%= f.submit "Publish your article >", class: "btn-blue"  %>
<% end %>

<div id="editor" contenteditable="true">buen</div>
<script type="text/javascript">
    editor = new Dante({ el: "editor"})
  editor.render()
</script>

app/views/articles/_quizz_banner.html.erb
<div class="quizz-banner";">
  <h3 id="typed-strings" class="title"></h3>
  <p class="center">Get customized suggestions</p>
  <%= link_to "Set preferences", new_quiz_path, class: "btn-wow" %>
</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container-fluid side-margin">
  <% if user_signed_in? && current_user.answered === false %>
    <div>
      <%= render 'quizz_banner' %>
    </div>
    <% else %>
      <div class=row>
        <div class="col-xs-12 index-titles">
          <a href="/articles">NΔTIONΔLL</a>
        </div>
      </div>
  <% end %>
    <%= render 'shared/filter' %>


<!-- <script>var playersrc;</script>
<iframe class="yt560x315" id="JSytplayer" src="https://www.youtube.com/embed/MVKts0fBW34?rel=0&controls=0&modestbranding=1&showinfo=0" onmouseover="this.src=playersrc+'&autoplay=1'" onmouseout="this.src=playersrc" frameborder="0" allowfullscreen></iframe>
 -->

  <div class="row margin-left">
    <% @articles.each_with_index do |article, index| %>
    <%= link_to article_path(article) do %>
    <% class_name = (index % 6 == 0) || ((index - 5) % 6 == 0) ? "col-xs-12 col-sm-6 col-md-4 col-lg-6" : "col-xs-12 col-sm-6 col-md-4 col-lg-3" %>
    <div class="card-wrapper">
      <div class="<%= class_name %>">
        <div class="card-container shadow">
          <% if article.picture.last(3) == 'jpg' || article.picture.last(4) == 'jpeg' || article.picture.last(3) == 'png' || article.picture.last(3) == 'gif' %>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.2)), url(<%= article.picture %>);">
              </div>
          <% else  %>

              <div class="card" style="background-image: url('https://img.youtube.com/vi/<%= article.picture.last(11) %>/hqdefault.jpg');">
                <iframe class="video" id="player" src="https://www.youtube.com/embed/<%= article.picture.last(11) %>?showinfo=0&controls=0&rel=0" onmouseover="this.src='https://www.youtube.com/embed/<%= article.picture.last(11)%>?showinfo=0&controls=0&rel=0&autoplay=1'" onmouseout="this.src='https://www.youtube.com/embed/<%= article.picture.last(11)%>?showinfo=0&controls=0&rel=0'" frameborder="0"></iframe>
              </div>

          <% end %>
          <div class="card-text grow">
            <div class="card-details color">
              <p> <%= article.category.name.upcase %></p>
              <!-- <p class="top-right"><%= article.publishing_date %></p> -->

              <% if article.avg_rating %>
                <ul class="list-inline top-right">
                  <% article.avg_rating.times do %>
                    <li class="list-inline-item"><i class="fas fa-star" style="color:#EDB867"></i></li>
                  <% end %>
                  <% unless article.avg_rating == 5 %>
                    <% (5 - article.avg_rating).times do %>
                      <li class="list-inline-item "><i class="fas fa-star" style="color:#d2d2d2"></i></li>
                    <% end %>
                  <% end %>
                </ul>
              <% end %>

            </div>
            <div class="card-titles color">
              <h5><%= truncate(article.title, length: 65) %></h5>
              <p><%= truncate(article.subtitle, length: 40) %></p>
            </div>
            <div class="card-profile">
              <div class="align-v">
              <div class="center">
                <img class="card-user" src=<%= article.user.picture %>>
              </div>
              <div class="user-details color">
                <div>
                  <p> <b><%= article.user.first_name%> <%= article.user.last_name %></b> </p>
                </div>
                <div>
                  <p> <%= article.user.city %></p>
                </div>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

<% content_for :after_js do %>

  <script>
    var playersrc = document.getElementById('player').src

    playersrc.hover ( playVideo, pauseVideo );

    function playVideo(e) {
      this.get(0).play();
    }

    function pauseVideo(e) {
      this.get(0).pause();
    }

  </script>

  <% if user_signed_in? && current_user.answered === false %>
    <%= javascript_pack_tag "typed" %>
  <% end %>

  <%= javascript_pack_tag "algolia" %>

<% end %>

app/views/articles/new.html.erb
<div class="white_background padding_bottom">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-lg-8 col-sm-offset-3 col-lg-offset-2">
        <div class="card-article">
        <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<!-- Article banner -->
<% if @article.picture %>
<% if @article.picture.last(3) == 'jpg' || @article.picture.last(4) == 'jpeg' || @article.picture.last(3) == 'png' || @article.picture.last(3) == 'gif' %>
<div class="article-banner" style="background-image: url(<%= @article.picture %>);">
</div>
<% else  %>
<div class="article-banner">
  <iframe id="media" src="<%= @article.picture %>" scrolling="no"></iframe>
</div>
<% end %>
<% end %>

<div class="container-fluid side-margin">
  <div class="row margin-left">

    <!-- LEFT SIDE -->
    <div class="col-xs-3 col-md-3 col-sm-3 sticky card-author-container">
      <div class="card-author">

        <!-- Profile of the writer -->
        <div class="article-profile">

          <div class="center author">
            <img class="card-user" src=<%= @article.user.picture %>>
          </div>

          <div class="user-details">
            <div class="author">
              <p><b><%= link_to "#{@article.user.first_name} #{@article.user.last_name}", user_path(@article.user) %></b> </p>
            </div>
            <div class="author">
              <p class="grow"> <%= @article.user.city %></p>
            </div>
          </div>

        </div>



        <div class="bio">
          <p> <%= @article.user.bio %></p>
        </div>

        <hr>

        <% if user_signed_in? && donation = Donation.find_by(user_id: current_user.id, article_id: @article.id) %>
        <div>
          <%= render 'articles/donation' %>
        </div>

        <% else %>
        <div id="form-donation">
          <%= simple_form_for [@article, @donation], remote: true do |f| %>
          <div id="donate-form">
            <div class="align-v align-h middle">
              <p id='euro'> €</p>
              <%= f.input :amount, label: false, input_html: { class: 'form_light no_border donate-value', value: '1.00' } %>
            </div>
            <h4> Support independent writing</h4>
            <%= button_tag(type: 'submit', class: "btn-blue-border") do %>
            Donate to <%= @article.user.first_name %>
            <% end %>
          </div>
          <% end %>
        </div>

        <hr>
        <% end %>
      </div>
    </div>



    <!-- RIGHT SIDE -->
    <div class="col-xs-8 col-md-8 col-sm-8 front">

      <!-- Article -->
      <div class="card-article">
        <!-- Articles informations -->
        <div class="article-text">
          <div class="article-details">
            <p> <%= @article.category.name.upcase %></p>
            <!-- Average Rating -->
            <% if @avg_rating %>
            <ul class="list-inline show-star-top-right">
              <% @avg_rating.times do %>
              <li class="list-inline-item"><i class="fas fa-star" style="color:#EDB867"></i></li>
              <% end %>
              <% unless @avg_rating == 5 %>
              <% (5 - @avg_rating).times do %>
              <li class="list-inline-item "><i class="fas fa-star" style="color:#d2d2d2"></i></li>
              <% end %>
              <% end %>
            </ul>
            <% end %>

          </div>

          <h1><%= @article.title %></h1>
          <h4><%= @article.subtitle %></h4>
          <p ><%= @article.publishing_date %></p>

          <hr>


          <h4>Summary</h4>
          <p> <%= @article.summary %></p>
        </div>

        <hr>

        <div>
          <h4>Full article</h4>
          <p><%= raw @article.content %></p>
        </div>
      </div>

      <!-- Rate the article-->
      <% if user_signed_in? %>
      <% unless Review.where(article: @article, user: current_user)[0] %>
      <div id="new-review-container">
        <hr>
        <h4>Rate the article</h4>
        <div id="new-review">
          <%= render 'reviews/form', article: @article, review: @review %>
        </div>
      </div>
      <% end %>
      <% end %>

      <!-- List of the reviews -->
      <% if @reviews.exists? %>
      <hr>
      <h4>All reviews</h4>
      <div id="reviews">
        <% @reviews.reverse.each do |review| %>
        <%= render 'reviews/show', article: @article, review: review %>
        <% end %>
      </div>
      <% else %>
      <div id="reviews"></div>
      <% end %>

      <% if @reviews.exists? && user_signed_in? == false%>
      <div class="link-on-right">
        <%= link_to "Sign in and rate this article", new_user_session_path %>
      </div>
      <% end %>


      <!-- Add an opinion -->
      <% if user_signed_in? %>
      <hr>
      <h4>Share your opinion </h4>
      <div id="new-opinion">
        <%= render 'opinions/form', article: @article, opinion: @opinion %>
      </div>
      <% end %>

      <!-- List of opinions -->
      <% if @opinions.exists? %>
      <hr>
      <h4>All opinions</h4>
      <div id="opinions">
        <% @opinions.reverse.each do |opinion| %>
        <%= render 'opinions/show', article: @article, opinion: opinion %>
        <% end %>
      </div>
      <% else %>
      <div id="opinions"></div>
      <% end %>

      <% if @opinions.exists? && user_signed_in? == false%>
      <div class="link-on-right">
        <%= link_to "Sign in and leave your opinion", new_user_session_path %>
      </div>
      <% end %>



      <!-- End buttons -->
      <div class="buttons">
        <% if user_signed_in? %>
        <% if policy(@article).edit? || current_user.admin? %>
        <%= link_to "Edit", edit_article_path(@article), class: "btn-blue-border" %>
        <% end %>

        <% if policy(@article).destroy? || current_user.admin? %>
        <%= link_to "Delete", article_path(@article), class: "btn-blue-border", method: :delete, data: { confirm: "Are you sure?"} %>
        <% end %>
        <% end %>
      </div>
    </div>

  </div>

</div>

<script>
  function triggerCardSticky() {
  // When the user scrolls the page, execute myFunction
  window.onscroll = function() {myFunction()};


}

// Add the sticky class to the navbar when you reach its scroll position. Remove "sticky" when you leave the scroll position
function myFunction() {
  // Get the article's card
  var card_article = document.getElementsByClassName('card-article')[0];
  var card_banner = document.getElementsByClassName('article-banner')[0];
  var card_author_container = document.getElementsByClassName('card-author-container')[0];

  // Get the offset position of the bottom of the article
  var sticky = card_banner.offsetTop + card_banner.offsetHeight + card_article.offsetHeight - 30;

  // Get the author's card

  // Get the offset position of the bottom of the author's card
  var card_author = document.getElementsByClassName('card-author')[0];
  var height = card_author.offsetHeight;
  var initial = card_author.offsetTop;

  if ((window.pageYOffset + height) >= sticky) {
    card_author_container.style.position = "relative";
    card_author.style.position = "absolute";
    card_author.style.top = (sticky - card_banner.offsetHeight - height - 60)+"px";
    card_author.classList.remove("sticky");
  } else {
   card_author_container.style.position = "sticky";
   card_author.style.position = "";
   card_author.classList.add("sticky");
 }
}

triggerCardSticky();
</script>