config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :donations, only: [:create, :destroy]
    resources :reviews, only: [:create]
    resources :opinions, only: [:create, :update, :destroy]
  end
  devise_for :users
  root to: 'pages#home'
  resources :quizzes, only: [:new]
  resources :categories_prefs, only: [:create]
  resource :emotion_prefs, only: [:update]
  resource :temperature_prefs, only: [:update]
  resources :users, only: [:show]
end

app/views/shared/_filter.html.erb
<% if current_page?('/articles') %>
<div class="filters">
  <% Category.all.each do |category| %>
  <div id="category">
    <%= link_to category.name, articles_path(category: category.name, avg_temperature: params[:avg_temperature], avg_emotion: params[:avg_emotion]) %>
  </div>
  <% end %>

    <!-- <div id="emotion">
      <div class="dropdown">
        <button class="dropbtn-emotion far fa-smile"></button>
        <div class="dropdown-content">
         <%= form_tag articles_path, class: 'fire-form', method: :get do %>
            <%= hidden_field_tag :category, params[:category] %>
            <%= hidden_field_tag :avg_temperature, params[:avg_temperature] %>
            <%= select_tag :avg_emotion, options_for_select([["😢", 1], ["😋", 2]]), onchange: 'changeEventHandler(event)' %>


            <input type="radio" class="hidden" value="1" name="review[emotion]" id="review_emotion_1">
              <label for="review_emotion_1" class="smiley" style="background-image: url(<%= asset_path 'sad_smiley.png' %>); width:50px; height: 50px;" style="cursor: pointer;">
              </label>
            <input type="radio" class="hidden" value="2" name="review[emotion]" id="review_emotion_2">
              <label for="review_emotion_2" class="smiley" style="background-image: url(<%= asset_path 'yay_smiley.png' %>); width:50px; height: 50px;" style="cursor: pointer;">
              </label>


              <select name="avg_emotion" id="avg_emotion" class="smiley" onchange="changeEventHandler(event)" style="display: none;">
                <option value="1">1</option>
                <option value="2">2</option>
              </select>


          <% end %>
        </div>
      </div>
    </div> -->

    <div id="emotion">
      <div class="dropdown">
        <button class="dropbtn-emotion">🤔</button>
        <div class="dropdown-content">
          <%= link_to "😢", articles_path(avg_emotion: 1, category: params[:category], avg_temperature: params[:avg_temperature]) %>
          <%= link_to "😊", articles_path(avg_emotion: 2, category: params[:category], avg_temperature: params[:avg_temperature])%>
        </div>
      </div>
    </div>

    <div id="temperature">
      <div class="dropdown">
        <button class="dropbtn-fire" style="font-size:25px ; margin-bottom:31px">
          <%= icon("fas", "fire") %>
        </button>
        <div class="dropdown-content">
          <%= link_to icon("fas", "fire"), articles_path(avg_emotion: params[:avg_emotion], category: params[:category], avg_temperature: 1) %>
          <%= link_to icon("fas", "fire"), articles_path(avg_emotion: params[:avg_emotion], category: params[:category], avg_temperature: 2)%>
          <%= link_to icon("fas", "fire"), articles_path(avg_emotion: params[:avg_emotion], category: params[:category], avg_temperature: 3) %>
          <%= link_to icon("fas", "fire"), articles_path(avg_emotion: params[:avg_emotion], category: params[:category], avg_temperature: 4)%>

<!--           <%= form_tag articles_path, class: 'fire-form', method: :get do %>
              <%= hidden_field_tag :category, params[:category] %>
              <%= hidden_field_tag :avg_emotion, params[:avg_emotion] %>
              <%= select_tag :avg_temperature, options_for_select(1..4), class: 'temperature-jquery', onchange: 'changeEventHandler(event)' %>
              <% end %> -->

            </div>
          </div>
        </div>

<!--     <div id="temperature">
      <div class="dropdown">
        <button class="dropbtn-fire fab fa-gripfire"></button>
        <div class="dropdown-content">
          <a><%= link_to "🔥🔥🔥🔥", articles_path(avg_temperature: 4, category: params[:category], avg_emotion: params[:avg_emotion]) %></a>
          <a><%= link_to "🔥🔥🔥", articles_path(avg_temperature: 3, category: params[:category], avg_emotion: params[:avg_emotion]) %></a>
          <a><%= link_to "🔥🔥", articles_path(avg_temperature: 2, category: params[:category], avg_emotion: params[:avg_emotion]) %></a>
          <a><%= link_to "🔥", articles_path(avg_temperature: 1, category: params[:category], avg_emotion: params[:avg_emotion]) %></a>
        </div>
      </div>
    </div> -->

  </div>
  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a target="_blank" href="https://www.facebook.com/become.european/?ref=bookmarks"><i class="fab fa fa-facebook"></i></a>
    <a target="_blank" href="https://twitter.com/_Nationall"><i class="fab fa fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    From Nationall, with <i class="fa fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<script src="//cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
<script src="//cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js"></script>

    <div class="navbar-wagon">

      <!-- Left Navigation -->
      <div class="navbar-left">
        <div>
          <%= link_to articles_path, class: "navbar-wagon-brand" do %>
          <%= image_tag "logo_blue.png", height: 50 %>
          <% end %>
        </div>
        <div>
          <%= form_tag articles_path, method: :get, class: "navbar-wagon-search" do %>
          <%= text_field_tag :query,
          params[:query],
          id: "search-input",
          class: "form-control navbar-search-input form_restaure_padding",
            placeholder: "Find articles here..."
            %>
            <% end %>
          </div>
        </div>

        <!-- Center Navigation -->
        <div class="align-h navbar-center">
          <div class="align-v width-map">
            <%= link_to "Map", root_path, class: "navbar-wagon-item navbar-wagon-link #{color_map}" %>
          </div>
          <div class="border-left align-v">
            <%= link_to "Articles", articles_path, class: "navbar-wagon-item navbar-wagon-link #{color_articles}" %>
          </div>
        </div>

        <!-- Right Navigation -->
        <div class="navbar-wagon-right hidden-xs">

          <% if user_signed_in? %>

          <!-- Links when logged in -->
          <%= link_to "Express yourself", new_article_path, class: "navbar-wagon-item navbar-wagon-link #{"page-active" if current_page?(controller: 'articles', action: 'new')}" %>

          <!-- Avatar with dropdown menu -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <% if current_user.picture %>
              <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <% end %>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li>
                  <%= link_to user_path(current_user), method: :get do %>
                  <i class="fas fa-user"></i>  <%= t(".profile", default: "Profile") %>
                  <% end %>
                </li>

                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
          <% else %>
          <!-- Login link (when logged out) -->
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <% end %>
        </div>

        <!-- Dropdown list appearing on mobile only -->
        <div class="navbar-wagon-item hidden -sm hidden-md hidden-lg">
          <div class="dropdown">
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><a href="#">Some mobile link</a></li>
              <li><a href="#">Other one</a></li>
              <li><a href="#">Other one</a></li>
            </ul>
          </div>
        </div>
      </div>